spring.application.name=NongLamFood

server.port=8080

# ===============================
# SQL SERVER
# ===============================

spring.datasource.url=jdbc:sqlserver://localhost:49473;databaseName=NongLamFood;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=Admin@123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===============================
# JWT
# ===============================

jwt.secret=1234567890123456789012345678901234567890123456789012345678901234

jwt.expiration=86400000

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#############################
# GMAIL
#############################

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=nguyenhoangquan0801@gmail.com

spring.mail.password=byxctacgtvimkgkv

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================
# GOOGLE LOGIN
# ==========================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}